export type SelectOption = { value: string; label: string };

export const languages: SelectOption[] = [
  { value: "aa", label: "Afar" },
  { value: "ab", label: "Abkhazian" },
  { value: "af", label: "Afrikaans" },
  { value: "ak", label: "Akan" },
  { value: "am", label: "Amharic" },
  { value: "ar", label: "Arabic" },
  { value: "as", label: "Assamese" },
  { value: "ay", label: "Aymara" },
  { value: "az", label: "Azerbaijani" },
  { value: "ba", label: "Bashkir" },
  { value: "be", label: "Belarusian" },
  { value: "bg", label: "Bulgarian" },
  { value: "bho", label: "Bhojpuri" },
  { value: "bm", label: "Bambara" },
  { value: "bn", label: "Bengali" },
  { value: "bo", label: "Tibetan" },
  { value: "br", label: "Breton" },
  { value: "bs", label: "Bosnian" },
  { value: "ca", label: "Catalan" },
  { value: "ceb", label: "Cebuano" },
  { value: "ckb", label: "Central Kurdish" },
  { value: "co", label: "Corsican" },
  { value: "cs", label: "Czech" },
  { value: "cy", label: "Welsh" },
  { value: "da", label: "Danish" },
  { value: "de", label: "German" },
  { value: "doi", label: "Dogri" },
  { value: "dv", label: "Divehi" },
  { value: "ee", label: "Ewe" },
  { value: "el", label: "Greek" },
  { value: "en", label: "English (US)" },
  { value: "eo", label: "Esperanto" },
  { value: "es", label: "Spanish" },
  { value: "et", label: "Estonian" },
  { value: "eu", label: "Basque" },
  { value: "fa", label: "Persian" },
  { value: "fi", label: "Finnish" },
  { value: "fil", label: "Filipino" },
  { value: "fj", label: "Fijian" },
  { value: "fo", label: "Faroese" },
  { value: "fr", label: "French" },
  { value: "fy", label: "Western Frisian" },
  { value: "ga", label: "Irish" },
  { value: "gd", label: "Scottish Gaelic" },
  { value: "gl", label: "Galician" },
  { value: "gn", label: "Guarani" },
  { value: "gom", label: "Goan Konkani" },
  { value: "gu", label: "Gujarati" },
  { value: "ha", label: "Hausa" },
  { value: "haw", label: "Hawaiian" },
  { value: "he", label: "Hebrew" },
  { value: "hi", label: "Hindi" },
  { value: "hmn", label: "Hmong" },
  { value: "hr", label: "Croatian" },
  { value: "ht", label: "Haitian Creole" },
  { value: "hu", label: "Hungarian" },
  { value: "hy", label: "Armenian" },
  { value: "id", label: "Indonesian" },
  { value: "ig", label: "Igbo" },
  { value: "ilo", label: "Ilocano" },
  { value: "is", label: "Icelandic" },
  { value: "it", label: "Italian" },
  { value: "ja", label: "Japanese" },
  { value: "jv", label: "Javanese" },
  { value: "ka", label: "Georgian" },
  { value: "kk", label: "Kazakh" },
  { value: "km", label: "Khmer" },
  { value: "kn", label: "Kannada" },
  { value: "ko", label: "Korean" },
  { value: "kri", label: "Krio" },
  { value: "ku", label: "Kurdish" },
  { value: "ky", label: "Kyrgyz" },
  { value: "la", label: "Latin" },
  { value: "lb", label: "Luxembourgish" },
  { value: "lg", label: "Ganda" },
  { value: "ln", label: "Lingala" },
  { value: "lo", label: "Lao" },
  { value: "lt", label: "Lithuanian" },
  { value: "lus", label: "Mizo" },
  { value: "lv", label: "Latvian" },
  { value: "mai", label: "Maithili" },
  { value: "mg", label: "Malagasy" },
  { value: "mi", label: "Maori" },
  { value: "mk", label: "Macedonian" },
  { value: "ml", label: "Malayalam" },
  { value: "mn", label: "Mongolian" },
  { value: "mni", label: "Manipuri" },
  { value: "mr", label: "Marathi" },
  { value: "ms", label: "Malay" },
  { value: "mt", label: "Maltese" },
  { value: "my", label: "Burmese" },
  { value: "ne", label: "Nepali" },
  { value: "nl", label: "Dutch" },
  { value: "no", label: "Norwegian" },
  { value: "nso", label: "Northern Sotho" },
  { value: "ny", label: "Nyanja" },
  { value: "om", label: "Oromo" },
  { value: "or", label: "Odia" },
  { value: "pa", label: "Punjabi" },
  { value: "pl", label: "Polish" },
  { value: "ps", label: "Pashto" },
  { value: "pt", label: "Portuguese" },
  { value: "qu", label: "Quechua" },
  { value: "ro", label: "Romanian" },
  { value: "ru", label: "Russian" },
  { value: "rw", label: "Kinyarwanda" },
  { value: "sa", label: "Sanskrit" },
  { value: "sd", label: "Sindhi" },
  { value: "si", label: "Sinhala" },
  { value: "sk", label: "Slovak" },
  { value: "sl", label: "Slovenian" },
  { value: "sm", label: "Samoan" },
  { value: "sn", label: "Shona" },
  { value: "so", label: "Somali" },
  { value: "sq", label: "Albanian" },
  { value: "sr", label: "Serbian" },
  { value: "st", label: "Southern Sotho" },
  { value: "su", label: "Sundanese" },
  { value: "sv", label: "Swedish" },
  { value: "sw", label: "Swahili" },
  { value: "ta", label: "Tamil" },
  { value: "te", label: "Telugu" },
  { value: "tg", label: "Tajik" },
  { value: "th", label: "Thai" },
  { value: "ti", label: "Tigrinya" },
  { value: "tk", label: "Turkmen" },
  { value: "tl", label: "Tagalog" },
  { value: "tr", label: "Turkish" },
  { value: "ts", label: "Tsonga" },
  { value: "tt", label: "Tatar" },
  { value: "ug", label: "Uyghur" },
  { value: "uk", label: "Ukrainian" },
  { value: "ur", label: "Urdu" },
  { value: "uz", label: "Uzbek" },
  { value: "vi", label: "Vietnamese" },
  { value: "xh", label: "Xhosa" },
  { value: "yi", label: "Yiddish" },
  { value: "yo", label: "Yoruba" },
  { value: "zh", label: "Chinese" },
  { value: "zu", label: "Zulu" },
];

export const currencies: SelectOption[] = [
  { value: "AED", label: "UAE Dirham (AED, د.إ)" },
  { value: "AFN", label: "Afghan Afghani (AFN, ؋)" },
  { value: "ALL", label: "Albanian Lek (ALL, L)" },
  { value: "AMD", label: "Armenian Dram (AMD, ֏)" },
  { value: "ANG", label: "Netherlands Antillean Guilder (ANG, ƒ)" },
  { value: "AOA", label: "Angolan Kwanza (AOA, Kz)" },
  { value: "ARS", label: "Argentine Peso (ARS, $)" },
  { value: "AUD", label: "Australian Dollar (AUD, $)" },
  { value: "AWG", label: "Aruban Florin (AWG, ƒ)" },
  { value: "AZN", label: "Azerbaijani Manat (AZN, ₼)" },
  { value: "BAM", label: "Bosnia-Herzegovina Convertible Mark (BAM, KM)" },
  { value: "BBD", label: "Barbadian Dollar (BBD, $)" },
  { value: "BDT", label: "Bangladeshi Taka (BDT, ৳)" },
  { value: "BGN", label: "Bulgarian Lev (BGN, лв)" },
  { value: "BHD", label: "Bahraini Dinar (BHD, .د.ب)" },
  { value: "BIF", label: "Burundian Franc (BIF, FBu)" },
  { value: "BMD", label: "Bermudian Dollar (BMD, $)" },
  { value: "BND", label: "Brunei Dollar (BND, $)" },
  { value: "BOB", label: "Bolivian Boliviano (BOB, Bs.)" },
  { value: "BRL", label: "Brazilian Real (BRL, R$)" },
  { value: "BSD", label: "Bahamian Dollar (BSD, $)" },
  { value: "BTN", label: "Bhutanese Ngultrum (BTN, Nu.)" },
  { value: "BWP", label: "Botswana Pula (BWP, P)" },
  { value: "BYN", label: "Belarusian Ruble (BYN, Br)" },
  { value: "BZD", label: "Belize Dollar (BZD, $)" },
  { value: "CAD", label: "Canadian Dollar (CAD, $)" },
  { value: "CDF", label: "Congolese Franc (CDF, FC)" },
  { value: "CHF", label: "Swiss Franc (CHF)" },
  { value: "CLP", label: "Chilean Peso (CLP, $)" },
  { value: "CNY", label: "Chinese Yuan (CNY, ¥)" },
  { value: "COP", label: "Colombian Peso (COP, $)" },
  { value: "CRC", label: "Costa Rican Colon (CRC, ₡)" },
  { value: "CUP", label: "Cuban Peso (CUP, $)" },
  { value: "CVE", label: "Cape Verdean Escudo (CVE, $)" },
  { value: "CZK", label: "Czech Koruna (CZK, Kč)" },
  { value: "DJF", label: "Djiboutian Franc (DJF, Fdj)" },
  { value: "DKK", label: "Danish Krone (DKK, kr)" },
  { value: "DOP", label: "Dominican Peso (DOP, $)" },
  { value: "DZD", label: "Algerian Dinar (DZD, د.ج)" },
  { value: "EGP", label: "Egyptian Pound (EGP, £)" },
  { value: "ERN", label: "Eritrean Nakfa (ERN, Nfk)" },
  { value: "ETB", label: "Ethiopian Birr (ETB, Br)" },
  { value: "EUR", label: "Euro (EUR, €)" },
  { value: "FJD", label: "Fijian Dollar (FJD, $)" },
  { value: "FKP", label: "Falkland Islands Pound (FKP, £)" },
  { value: "GBP", label: "British Pound (GBP, £)" },
  { value: "GEL", label: "Georgian Lari (GEL, ₾)" },
  { value: "GHS", label: "Ghanaian Cedi (GHS, ₵)" },
  { value: "GIP", label: "Gibraltar Pound (GIP, £)" },
  { value: "GMD", label: "Gambian Dalasi (GMD, D)" },
  { value: "GNF", label: "Guinean Franc (GNF, FG)" },
  { value: "GTQ", label: "Guatemalan Quetzal (GTQ, Q)" },
  { value: "GYD", label: "Guyanese Dollar (GYD, $)" },
  { value: "HKD", label: "Hong Kong Dollar (HKD, $)" },
  { value: "HNL", label: "Honduran Lempira (HNL, L)" },
  { value: "HTG", label: "Haitian Gourde (HTG, G)" },
  { value: "HUF", label: "Hungarian Forint (HUF, Ft)" },
  { value: "IDR", label: "Indonesian Rupiah (IDR, Rp)" },
  { value: "ILS", label: "Israeli New Shekel (ILS, ₪)" },
  { value: "INR", label: "Indian Rupee (INR, ₹)" },
  { value: "IQD", label: "Iraqi Dinar (IQD, ع.د)" },
  { value: "IRR", label: "Iranian Rial (IRR, ﷼)" },
  { value: "ISK", label: "Icelandic Krona (ISK, kr)" },
  { value: "JMD", label: "Jamaican Dollar (JMD, $)" },
  { value: "JOD", label: "Jordanian Dinar (JOD, د.ا)" },
  { value: "JPY", label: "Japanese Yen (JPY, ¥)" },
  { value: "KES", label: "Kenyan Shilling (KES, KSh)" },
  { value: "KGS", label: "Kyrgyzstani Som (KGS, сом)" },
  { value: "KHR", label: "Cambodian Riel (KHR, ៛)" },
  { value: "KMF", label: "Comorian Franc (KMF, CF)" },
  { value: "KPW", label: "North Korean Won (KPW, ₩)" },
  { value: "KRW", label: "South Korean Won (KRW, ₩)" },
  { value: "KWD", label: "Kuwaiti Dinar (KWD, د.ك)" },
  { value: "KYD", label: "Cayman Islands Dollar (KYD, $)" },
  { value: "KZT", label: "Kazakhstani Tenge (KZT, ₸)" },
  { value: "LAK", label: "Lao Kip (LAK, ₭)" },
  { value: "LBP", label: "Lebanese Pound (LBP, ل.ل)" },
  { value: "LKR", label: "Sri Lankan Rupee (LKR, Rs)" },
  { value: "LRD", label: "Liberian Dollar (LRD, $)" },
  { value: "LSL", label: "Lesotho Loti (LSL, L)" },
  { value: "LYD", label: "Libyan Dinar (LYD, ل.د)" },
  { value: "MAD", label: "Moroccan Dirham (MAD, د.م.)" },
  { value: "MDL", label: "Moldovan Leu (MDL, L)" },
  { value: "MGA", label: "Malagasy Ariary (MGA, Ar)" },
  { value: "MKD", label: "Macedonian Denar (MKD, ден)" },
  { value: "MMK", label: "Myanmar Kyat (MMK, K)" },
  { value: "MNT", label: "Mongolian Tugrik (MNT, ₮)" },
  { value: "MOP", label: "Macanese Pataca (MOP, MOP$)" },
  { value: "MRU", label: "Mauritanian Ouguiya (MRU, UM)" },
  { value: "MUR", label: "Mauritian Rupee (MUR, ₨)" },
  { value: "MVR", label: "Maldivian Rufiyaa (MVR, Rf)" },
  { value: "MWK", label: "Malawian Kwacha (MWK, MK)" },
  { value: "MXN", label: "Mexican Peso (MXN, $)" },
  { value: "MYR", label: "Malaysian Ringgit (MYR, RM)" },
  { value: "MZN", label: "Mozambican Metical (MZN, MT)" },
  { value: "NAD", label: "Namibian Dollar (NAD, $)" },
  { value: "NGN", label: "Nigerian Naira (NGN, ₦)" },
  { value: "NIO", label: "Nicaraguan Cordoba (NIO, C$)" },
  { value: "NOK", label: "Norwegian Krone (NOK, kr)" },
  { value: "NPR", label: "Nepalese Rupee (NPR, ₨)" },
  { value: "NZD", label: "New Zealand Dollar (NZD, $)" },
  { value: "OMR", label: "Omani Rial (OMR, ر.ع.)" },
  { value: "PAB", label: "Panamanian Balboa (PAB, B/.)" },
  { value: "PEN", label: "Peruvian Sol (PEN, S/)" },
  { value: "PGK", label: "Papua New Guinean Kina (PGK, K)" },
  { value: "PHP", label: "Philippine Peso (PHP, ₱)" },
  { value: "PKR", label: "Pakistani Rupee (PKR, ₨)" },
  { value: "PLN", label: "Polish Zloty (PLN, zł)" },
  { value: "PYG", label: "Paraguayan Guarani (PYG, ₲)" },
  { value: "QAR", label: "Qatari Riyal (QAR, ر.ق)" },
  { value: "RON", label: "Romanian Leu (RON, lei)" },
  { value: "RSD", label: "Serbian Dinar (RSD, дин)" },
  { value: "RUB", label: "Russian Ruble (RUB, ₽)" },
  { value: "RWF", label: "Rwandan Franc (RWF, RF)" },
  { value: "SAR", label: "Saudi Riyal (SAR, ر.س)" },
  { value: "SBD", label: "Solomon Islands Dollar (SBD, $)" },
  { value: "SCR", label: "Seychellois Rupee (SCR, ₨)" },
  { value: "SDG", label: "Sudanese Pound (SDG, ج.س.)" },
  { value: "SEK", label: "Swedish Krona (SEK, kr)" },
  { value: "SGD", label: "Singapore Dollar (SGD, $)" },
  { value: "SHP", label: "Saint Helena Pound (SHP, £)" },
  { value: "SLE", label: "Sierra Leonean Leone (SLE, Le)" },
  { value: "SOS", label: "Somali Shilling (SOS, Sh)" },
  { value: "SRD", label: "Surinamese Dollar (SRD, $)" },
  { value: "SSP", label: "South Sudanese Pound (SSP, £)" },
  { value: "STN", label: "Sao Tome and Principe Dobra (STN, Db)" },
  { value: "SYP", label: "Syrian Pound (SYP, £)" },
  { value: "SZL", label: "Swazi Lilangeni (SZL, L)" },
  { value: "THB", label: "Thai Baht (THB, ฿)" },
  { value: "TJS", label: "Tajikistani Somoni (TJS, SM)" },
  { value: "TMT", label: "Turkmenistani Manat (TMT, m)" },
  { value: "TND", label: "Tunisian Dinar (TND, د.ت)" },
  { value: "TOP", label: "Tongan Paʻanga (TOP, T$)" },
  { value: "TRY", label: "Turkish Lira (TRY, ₺)" },
  { value: "TTD", label: "Trinidad and Tobago Dollar (TTD, $)" },
  { value: "TWD", label: "New Taiwan Dollar (TWD, NT$)" },
  { value: "TZS", label: "Tanzanian Shilling (TZS, TSh)" },
  { value: "UAH", label: "Ukrainian Hryvnia (UAH, ₴)" },
  { value: "UGX", label: "Ugandan Shilling (UGX, USh)" },
  { value: "USD", label: "US Dollar (USD, $)" },
  { value: "UYU", label: "Uruguayan Peso (UYU, $U)" },
  { value: "UZS", label: "Uzbekistani Som (UZS, soʻm)" },
  { value: "VES", label: "Venezuelan Bolivar (VES, Bs.)" },
  { value: "VND", label: "Vietnamese Dong (VND, ₫)" },
  { value: "VUV", label: "Vanuatu Vatu (VUV, VT)" },
  { value: "WST", label: "Samoan Tala (WST, WS$)" },
  { value: "XAF", label: "Central African CFA Franc (XAF, FCFA)" },
  { value: "XCD", label: "East Caribbean Dollar (XCD, $)" },
  { value: "XOF", label: "West African CFA Franc (XOF, CFA)" },
  { value: "XPF", label: "CFP Franc (XPF, ₣)" },
  { value: "YER", label: "Yemeni Rial (YER, ﷼)" },
  { value: "ZAR", label: "South African Rand (ZAR, R)" },
  { value: "ZMW", label: "Zambian Kwacha (ZMW, ZK)" },
  { value: "ZWL", label: "Zimbabwean Dollar (ZWL, $)" },
];

export const cryptoCurrencies: SelectOption[] = [
  { value: "USDC", label: "USD Coin (USDC)" },
  { value: "USDT", label: "Tether (USDT)" },
  { value: "BTC", label: "Bitcoin (BTC)" },
  { value: "ETH", label: "Ethereum (ETH)" },
  { value: "SOL", label: "Solana (SOL)" },
];


