[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
apex_protocol = "D643vETCKW14hgvpmUoWZTYi65R9tijNm1RGmZFfS6g1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/apex-fresh-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
