[package]
name = "mock_oracle"
version = "0.1.0"
description = "Mock Pyth-layout oracle for devnet ApeX"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "mock_oracle"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]

[dependencies]
solana-program = "1.18"